// 官网运营配置。域名、API、二维码和协议链接在个人部署时填写。
window.DAYKEEP_SITE_CONFIG = {
  environments: {
    production: {
      hosts: [],
      label: '',
      miniProgramName: '只我们',
      latestVersion: '即将发布',
      releasedAt: '筹备中',
      apiBase: '',
      iosUrl: '',
      androidUrl: '',
      miniProgramQr: '',
      miniProgramQrExpiresAt: '',
      accessNotice: '',
      supportEmail: '',
      supportWechat: '',
      privacyUrl: '',
      agreementUrl: '',
    },
    testing: {
      hosts: ['localhost', '127.0.0.1'],
      label: '',
      miniProgramName: '只我们',
      latestVersion: '本地预览',
      releasedAt: '尚未发布',
      apiBase: '',
      iosUrl: '',
      androidUrl: '',
      miniProgramQr: '',
      miniProgramQrExpiresAt: '',
      accessNotice: '',
      supportEmail: '',
      supportWechat: '',
      privacyUrl: '',
      agreementUrl: '',
    },
  },
}
